"""add field sources

Revision ID: 0cd940f34283
Revises: 8520f097a820
Create Date: 2026-02-06 15:49:00.468830

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0cd940f34283'
down_revision: Union[str, None] = '8520f097a820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('field_key', sa.String(length=200), nullable=False),
    sa.Column('field_path', sa.String(length=500), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_json', sa.JSON(), nullable=True),
    sa.Column('source_type', sa.Enum('OFFICIAL_WEBSITE', 'GOVERNMENT', 'COMMUNITY_FORUM', 'PARENT_SUBMITTED', 'SCHOOL_CONTACT', 'SCRAPED_WEBSITE', 'UNKNOWN', name='sourcetype'), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('display_url', sa.String(length=300), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.Column('last_verified', sa.DateTime(), nullable=True),
    sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'CONFLICTING', name='sourceconfidence'), nullable=True),
    sa.Column('submitted_by', sa.String(length=200), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('field_sources')
    # ### end Alembic commands ###
