"""location age group shifts

Revision ID: 1c4c6698b9bd
Revises: b3f56be53b4a
Create Date: 2026-02-10 16:20:01.388951

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1c4c6698b9bd'
down_revision: Union[str, None] = 'b3f56be53b4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_age_group_shifts',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('age_group', sa.String(length=50), nullable=False),
    sa.Column('shift', sa.String(length=50), nullable=True),
    sa.Column('has_organised_groups', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['school_locations.id'], ),
    sa.PrimaryKeyConstraint('location_id', 'age_group')
    )
    op.execute("""
        INSERT INTO location_age_group_shifts (location_id, age_group, shift, has_organised_groups)
        SELECT lag.location_id, lag.age_group, sl.shift, sl.has_organised_groups
        FROM location_age_groups AS lag
        JOIN school_locations AS sl ON sl.id = lag.location_id
    """)
    op.drop_table('location_age_groups')
    op.drop_column('school_locations', 'has_organised_groups')
    op.drop_column('school_locations', 'shift')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_locations', sa.Column('shift', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('school_locations', sa.Column('has_organised_groups', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_table('location_age_groups',
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('age_group', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['school_locations.id'], name=op.f('location_age_groups_location_id_fkey')),
    sa.PrimaryKeyConstraint('location_id', 'age_group', name=op.f('location_age_groups_pkey'))
    )
    op.execute("""
        INSERT INTO location_age_groups (location_id, age_group)
        SELECT location_id, age_group
        FROM location_age_group_shifts
    """)
    op.execute("""
        UPDATE school_locations
        SET shift = sub.shift, has_organised_groups = sub.has_organised_groups
        FROM (
            SELECT location_id, MIN(shift) AS shift, MIN(has_organised_groups) AS has_organised_groups
            FROM location_age_group_shifts
            GROUP BY location_id
        ) AS sub
        WHERE school_locations.id = sub.location_id
    """)
    op.drop_table('location_age_group_shifts')
    # ### end Alembic commands ###
