"""add location tags

Revision ID: 23a77dcbe004
Revises: 1c4c6698b9bd
Create Date: 2026-02-10 18:11:06.818710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23a77dcbe004'
down_revision: Union[str, None] = '1c4c6698b9bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_locations', sa.Column('location_tags', sa.JSON(), nullable=True))
    op.drop_index(op.f('uq_source_pages_discovery'), table_name='source_pages', postgresql_where='(school_id IS NULL)')
    op.drop_index(op.f('uq_source_pages_school'), table_name='source_pages', postgresql_where='(school_id IS NOT NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_source_pages_school'), 'source_pages', ['school_id', 'scrape_type', 'source_url'], unique=True, postgresql_where='(school_id IS NOT NULL)')
    op.create_index(op.f('uq_source_pages_discovery'), 'source_pages', ['scrape_type', 'source_url'], unique=True, postgresql_where='(school_id IS NULL)')
    op.drop_column('school_locations', 'location_tags')
    # ### end Alembic commands ###
