"""add geocode meta to school locations

Revision ID: 5918fe5e78bb
Revises: c5931c21a22c
Create Date: 2026-07-08 16:02:57.270404

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5918fe5e78bb'
down_revision: Union[str, None] = 'c5931c21a22c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_locations', sa.Column('geocode_meta', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school_locations', 'geocode_meta')
    # ### end Alembic commands ###
