"""add pipeline heartbeat and provider cost ledger

Revision ID: 5ac75d912125
Revises: 6cb27777e0d2
Create Date: 2026-07-20 15:30:23.344280

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5ac75d912125'
down_revision: Union[str, None] = '6cb27777e0d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_request_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_request_id', sa.String(length=36), nullable=False),
    sa.Column('provider_request_id', sa.String(length=255), nullable=True),
    sa.Column('pipeline_run_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('provider_cost_usd', sa.Numeric(precision=14, scale=8), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ATTRIBUTED', 'UNCERTAIN', name='providerrequeststatus'), nullable=False),
    sa.Column('uncertainty_reason', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attributed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_request_id', name='uq_provider_request_ledger_client_request_id'),
    sa.UniqueConstraint('provider_request_id', name='uq_provider_request_ledger_provider_request_id')
    )
    op.create_index(op.f('ix_provider_request_ledger_pipeline_run_id'), 'provider_request_ledger', ['pipeline_run_id'], unique=False)
    op.add_column('pipeline_runs', sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pipeline_runs', sa.Column('last_completed_stage', sa.String(length=50), nullable=True))
    op.add_column('pipeline_runs', sa.Column('terminalization_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_runs', 'terminalization_reason')
    op.drop_column('pipeline_runs', 'last_completed_stage')
    op.drop_column('pipeline_runs', 'heartbeat_at')
    op.drop_index(op.f('ix_provider_request_ledger_pipeline_run_id'), table_name='provider_request_ledger')
    op.drop_table('provider_request_ledger')
    # ### end Alembic commands ###
