"""add registry scrape type

Revision ID: 5be6de86fd49
Revises: 23a77dcbe004
Create Date: 2026-02-12 15:44:51.339282

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5be6de86fd49'
down_revision: Union[str, None] = '23a77dcbe004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE scrapetype ADD VALUE IF NOT EXISTS 'REGISTRY'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
