"""add confidence score to field sources

Revision ID: 5c6e9ae0d1f1
Revises: f3fdc4438b69
Create Date: 2026-02-09 14:05:46.059057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c6e9ae0d1f1'
down_revision: Union[str, None] = 'f3fdc4438b69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('field_sources', sa.Column('confidence_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('field_sources', 'confidence_score')
    # ### end Alembic commands ###
