"""add pipeline_runs.metrics column

Revision ID: 6cb27777e0d2
Revises: 5918fe5e78bb
Create Date: 2026-07-09 12:40:51.891522

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6cb27777e0d2'
down_revision: Union[str, None] = '5918fe5e78bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_runs', sa.Column('metrics', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_runs', 'metrics')
    # ### end Alembic commands ###
