"""add name_en and address_en columns

Revision ID: 73e7144d4f81
Revises: 0b2d14119b5e
Create Date: 2026-02-04 16:41:37.812118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73e7144d4f81'
down_revision: Union[str, None] = '0b2d14119b5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exam_results', 'scraped_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_exam_results_school_id'), table_name='exam_results')
    op.drop_constraint(op.f('exam_results_school_id_fkey'), 'exam_results', type_='foreignkey')
    op.create_foreign_key(None, 'exam_results', 'schools', ['school_id'], ['id'])
    op.alter_column('pricing', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('pricing', 'scraped_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_pricing_school_id'), table_name='pricing')
    op.drop_constraint(op.f('pricing_school_id_fkey'), 'pricing', type_='foreignkey')
    op.create_foreign_key(None, 'pricing', 'schools', ['school_id'], ['id'])
    op.add_column('school_locations', sa.Column('address_en', sa.String(length=500), nullable=True))
    op.alter_column('school_locations', 'is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_school_locations_age_group'), table_name='school_locations')
    op.drop_index(op.f('ix_school_locations_school_id'), table_name='school_locations')
    op.drop_constraint(op.f('school_locations_school_id_fkey'), 'school_locations', type_='foreignkey')
    op.create_foreign_key(None, 'school_locations', 'schools', ['school_id'], ['id'])
    op.add_column('schools', sa.Column('name_en', sa.String(length=500), nullable=True))
    op.alter_column('schools', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('schools', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('scrape_log', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('scrape_log', 'scraped_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_scrape_log_school_id'), table_name='scrape_log')
    op.drop_index(op.f('ix_scrape_log_scraped_at'), table_name='scrape_log')
    op.drop_constraint(op.f('scrape_log_school_id_fkey'), 'scrape_log', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('scrape_log_school_id_fkey'), 'scrape_log', 'schools', ['school_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_scrape_log_scraped_at'), 'scrape_log', ['scraped_at'], unique=False)
    op.create_index(op.f('ix_scrape_log_school_id'), 'scrape_log', ['school_id'], unique=False)
    op.alter_column('scrape_log', 'scraped_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scrape_log', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('schools', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('schools', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('schools', 'name_en')
    op.drop_constraint(None, 'school_locations', type_='foreignkey')
    op.create_foreign_key(op.f('school_locations_school_id_fkey'), 'school_locations', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_school_locations_school_id'), 'school_locations', ['school_id'], unique=False)
    op.create_index(op.f('ix_school_locations_age_group'), 'school_locations', ['age_group'], unique=False)
    op.alter_column('school_locations', 'is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('school_locations', 'address_en')
    op.drop_constraint(None, 'pricing', type_='foreignkey')
    op.create_foreign_key(op.f('pricing_school_id_fkey'), 'pricing', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_pricing_school_id'), 'pricing', ['school_id'], unique=False)
    op.alter_column('pricing', 'scraped_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('pricing', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.drop_constraint(None, 'exam_results', type_='foreignkey')
    op.create_foreign_key(op.f('exam_results_school_id_fkey'), 'exam_results', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_exam_results_school_id'), 'exam_results', ['school_id'], unique=False)
    op.alter_column('exam_results', 'scraped_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
