"""extend pricing fields

Revision ID: 8ba45757e632
Revises: c7ae86e806b7
Create Date: 2026-02-09 16:05:39.042142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ba45757e632'
down_revision: Union[str, None] = 'c7ae86e806b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE pricecategory ADD VALUE IF NOT EXISTS 'REGISTRATION'")
    op.execute("ALTER TYPE pricecategory ADD VALUE IF NOT EXISTS 'MATERIALS'")
    op.execute("ALTER TYPE pricecategory ADD VALUE IF NOT EXISTS 'EXTENDED_DAY'")
    op.execute("ALTER TYPE pricecategory ADD VALUE IF NOT EXISTS 'UNIFORMS'")
    op.execute("ALTER TYPE pricecategory ADD VALUE IF NOT EXISTS 'EXTRACURRICULAR'")
    op.execute("ALTER TYPE pricecategory ADD VALUE IF NOT EXISTS 'CAMP'")
    op.execute("ALTER TYPE priceperiod ADD VALUE IF NOT EXISTS 'QUARTER'")
    op.add_column('pricing', sa.Column('academic_year', sa.String(length=20), nullable=True))
    op.add_column('pricing', sa.Column('amount_min', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('pricing', sa.Column('amount_max', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('pricing', sa.Column('plan_name', sa.String(length=100), nullable=True))
    op.add_column('pricing', sa.Column('pricing_context', sa.JSON(), nullable=True))
    op.alter_column('pricing', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: Postgres enums cannot easily drop values; leaving added values in place.
    op.alter_column('pricing', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.drop_column('pricing', 'pricing_context')
    op.drop_column('pricing', 'plan_name')
    op.drop_column('pricing', 'amount_max')
    op.drop_column('pricing', 'amount_min')
    op.drop_column('pricing', 'academic_year')
    # ### end Alembic commands ###
