"""allow unstated pricing period

Revision ID: 9926b4854ed3
Revises: a5ec17ca7a06
Create Date: 2026-09-18 16:07:15.871648

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9926b4854ed3'
down_revision: Union[str, None] = 'a5ec17ca7a06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pricing', 'period',
               existing_type=postgresql.ENUM('MONTHLY', 'YEARLY', 'ONE_TIME', 'QUARTER', 'TERM', 'SEMESTER', name='priceperiod'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Restoring NOT NULL would need a period for every row that has none, and the only
    # way to get one is to invent it. Refuse instead: a guessed period is exactly what
    # this revision exists to stop publishing.
    unstated = op.get_bind().execute(
        sa.text("SELECT count(*) FROM pricing WHERE period IS NULL")
    ).scalar_one()
    if unstated:
        raise RuntimeError(
            f"Refusing to downgrade: {unstated} pricing row(s) have no stated period. "
            "Restoring NOT NULL would require inventing a period for them. Resolve those "
            "rows explicitly (for example by re-extracting or deleting them) and retry."
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pricing', 'period',
               existing_type=postgresql.ENUM('MONTHLY', 'YEARLY', 'ONE_TIME', 'QUARTER', 'TERM', 'SEMESTER', name='priceperiod'),
               nullable=False)
    # ### end Alembic commands ###
