"""add pricing source_page_id evidence link

Revision ID: a5ec17ca7a06
Revises: 5ac75d912125
Create Date: 2026-09-17 16:08:48.761433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5ec17ca7a06'
down_revision: Union[str, None] = '5ac75d912125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricing', sa.Column('source_page_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_pricing_source_page_id',
        'pricing',
        'source_pages',
        ['source_page_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_pricing_source_page_id', 'pricing', type_='foreignkey')
    op.drop_column('pricing', 'source_page_id')
    # ### end Alembic commands ###
