"""add location age groups

Revision ID: b3f56be53b4a
Revises: ebdc1c57cdac
Create Date: 2026-02-10 16:07:19.806021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3f56be53b4a'
down_revision: Union[str, None] = 'ebdc1c57cdac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_age_groups',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('age_group', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['school_locations.id'], ),
    sa.PrimaryKeyConstraint('location_id', 'age_group')
    )
    op.execute("""
        INSERT INTO location_age_groups (location_id, age_group)
        SELECT id, age_group
        FROM school_locations
        WHERE age_group IS NOT NULL
    """)
    op.drop_column('school_locations', 'age_group')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_locations', sa.Column('age_group', sa.String(length=50), nullable=True))
    op.execute("""
        UPDATE school_locations
        SET age_group = sub.age_group
        FROM (
            SELECT location_id, MIN(age_group) AS age_group
            FROM location_age_groups
            GROUP BY location_id
        ) AS sub
        WHERE school_locations.id = sub.location_id
    """)
    op.alter_column('school_locations', 'age_group', nullable=False)
    op.drop_table('location_age_groups')
    # ### end Alembic commands ###
