"""add source_pages and source_url to scrape_log

Revision ID: c7ae86e806b7
Revises: 5c6e9ae0d1f1
Create Date: 2026-02-09 15:32:53.966141

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c7ae86e806b7'
down_revision: Union[str, None] = '5c6e9ae0d1f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    scrape_type_enum = postgresql.ENUM(
        'DISCOVERY', 'WEBSITE', 'PRICES', 'NVO', 'SOCIAL', name='scrapetype', create_type=False
    )
    op.create_table('source_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('scrape_type', scrape_type_enum, nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scrape_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        'uq_source_pages_school',
        'source_pages',
        ['school_id', 'scrape_type', 'source_url'],
        unique=True,
        postgresql_where=sa.text('school_id IS NOT NULL'),
    )
    op.create_index(
        'uq_source_pages_discovery',
        'source_pages',
        ['scrape_type', 'source_url'],
        unique=True,
        postgresql_where=sa.text('school_id IS NULL'),
    )
    op.drop_column('schools', 'page_hash')
    op.add_column('scrape_log', sa.Column('source_url', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scrape_log', 'source_url')
    op.add_column('schools', sa.Column('page_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_index('uq_source_pages_discovery', table_name='source_pages')
    op.drop_index('uq_source_pages_school', table_name='source_pages')
    op.drop_table('source_pages')
    # ### end Alembic commands ###
