"""add country and i18n fields

Revision ID: f3fdc4438b69
Revises: 0cd940f34283
Create Date: 2026-02-07 00:03:14.934824

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f3fdc4438b69'
down_revision: Union[str, None] = '0cd940f34283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name_i18n', sa.JSON(), nullable=False),
    sa.Column('education_config', sa.JSON(), nullable=False),
    sa.Column('map_config', sa.JSON(), nullable=False),
    sa.Column('supported_languages', sa.JSON(), nullable=False),
    sa.Column('default_language', sa.String(length=5), nullable=False),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.alter_column('exam_results', 'exam_type',
               existing_type=postgresql.ENUM('NVO_4', 'NVO_7', 'NVO_10', name='examtype'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('pricing', 'age_group',
               existing_type=postgresql.ENUM('NURSERY', 'FIRST', 'SECOND', 'THIRD', 'PRESCHOOL', 'GRADE_1_4', 'GRADE_5_7', 'GRADE_8_12', name='agegroup'),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.add_column('school_locations', sa.Column('address_i18n', sa.JSON(), nullable=False))
    op.alter_column('school_locations', 'age_group',
               existing_type=postgresql.ENUM('NURSERY', 'FIRST', 'SECOND', 'THIRD', 'PRESCHOOL', 'GRADE_1_4', 'GRADE_5_7', 'GRADE_8_12', name='agegroup'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('school_locations', 'shift',
               existing_type=postgresql.ENUM('MORNING', 'AFTERNOON', 'FULL_DAY', name='shift'),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_column('school_locations', 'address_en')
    op.drop_column('school_locations', 'address')
    op.add_column('schools', sa.Column('country_code', sa.String(length=2), nullable=False))
    op.add_column('schools', sa.Column('name_i18n', sa.JSON(), nullable=False))
    op.add_column('schools', sa.Column('summary_i18n', sa.JSON(), nullable=True))
    op.alter_column('schools', 'school_type',
               existing_type=postgresql.ENUM('STATE', 'PRIVATE', 'INTERNATIONAL', name='schooltype'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('schools', 'education_level',
               existing_type=postgresql.ENUM('NURSERY', 'KINDERGARTEN', 'PRIMARY', 'LOWER_SECONDARY', 'UPPER_SECONDARY', name='educationlevel'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_foreign_key(None, 'schools', 'countries', ['country_code'], ['code'])
    op.drop_column('schools', 'summary_en')
    op.drop_column('schools', 'name_en')
    op.drop_column('schools', 'summary_bg')
    op.drop_column('schools', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('name', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('schools', sa.Column('summary_bg', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('schools', sa.Column('name_en', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('schools', sa.Column('summary_en', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'schools', type_='foreignkey')
    op.alter_column('schools', 'education_level',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('NURSERY', 'KINDERGARTEN', 'PRIMARY', 'LOWER_SECONDARY', 'UPPER_SECONDARY', name='educationlevel'),
               existing_nullable=False)
    op.alter_column('schools', 'school_type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('STATE', 'PRIVATE', 'INTERNATIONAL', name='schooltype'),
               existing_nullable=False)
    op.drop_column('schools', 'summary_i18n')
    op.drop_column('schools', 'name_i18n')
    op.drop_column('schools', 'country_code')
    op.add_column('school_locations', sa.Column('address', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('school_locations', sa.Column('address_en', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.alter_column('school_locations', 'shift',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('MORNING', 'AFTERNOON', 'FULL_DAY', name='shift'),
               existing_nullable=True)
    op.alter_column('school_locations', 'age_group',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('NURSERY', 'FIRST', 'SECOND', 'THIRD', 'PRESCHOOL', 'GRADE_1_4', 'GRADE_5_7', 'GRADE_8_12', name='agegroup'),
               existing_nullable=False)
    op.drop_column('school_locations', 'address_i18n')
    op.alter_column('pricing', 'age_group',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('NURSERY', 'FIRST', 'SECOND', 'THIRD', 'PRESCHOOL', 'GRADE_1_4', 'GRADE_5_7', 'GRADE_8_12', name='agegroup'),
               existing_nullable=True)
    op.alter_column('exam_results', 'exam_type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('NVO_4', 'NVO_7', 'NVO_10', name='examtype'),
               existing_nullable=False)
    op.drop_table('countries')
    # ### end Alembic commands ###
